import React, { Component } from 'react';
import { Tabs, Tab, OverlayTrigger, Tooltip } from 'react-bootstrap';
import { Terminal, CheckCircle } from 'react-feather';
import './UserConsole.css';

class UserConsole extends Component {

    createTooltip = (trigger, id, tooltip) => {
        return(
            <OverlayTrigger
                placement="top"
                overlay={
                    <Tooltip id={id}>
                        {tooltip}
                    </Tooltip>
                }
                >
                {trigger}
            </OverlayTrigger>
        );
    }

    render(){
        const {onBottomTab, currBottomTab} = this.props;

        return(
                <Tabs defaultActiveKey={currBottomTab} id="console-test-tab" onSelect={onBottomTab}>
                    <Tab eventKey="tests" title={this.createTooltip(<span><CheckCircle size={16} /> Test Output</span>, "tooltip-test", "The output generated by the testsuite")}>
                        <div id="logger" className="light">
                            <div className="logger-section">
                                <h6><CheckCircle size={16} /> Test Output</h6><br/>
                                <span className="">{this.props.err}</span>
                            </div>
                        </div>
                    </Tab>
                    <Tab eventKey="console" title={this.createTooltip(<span><Terminal size={16} /> Console Output</span>, "tooltip-console", "The console output of the currently open file")}>
                        <div id="logger" className="mt-4">
                            <div className="logger-section">
                                <h6><Terminal size={16} /> Console Output</h6><br/>
                                <span className="log">{this.props.log}</span>
                            </div>
                        </div>
                    </Tab>
                </Tabs>
        );
    }
};

export default UserConsole;